### ISSUE TITLE
Comment on the project

### ISSUE THREAD

**Issue by quaeritis** [HelgeGehring/gdshelpers#2]
First of all, I think the project is pretty great.

I've been thinking for a long time about the fact that there is currently no Python package that allows easy layout creation and future-proof. The biggest counterpoint for me has always been that most packages do not support OASIS.

Somehow I had overslept the start of their project. And therefore I myself made a lot of thoughts on the subject. I would like to share this, maybe that's helpful in some way  (if not just ignoring).

My current state is that I use the [Klayout Python API](https://github.com/KLayout/klayout/wiki/KLayout-Python-Module). This offers a lot of different supported file formats (gds2, OASIS, etc). The C ++ implementation of the library may offer performance benefits for very large layouts (not tested).

Unfortunately, the disadvantages are pretty big too, the Klayout C ++ Geometry API is an integral part of Klayout and not a shared library. In addition, the Python API interface with a self-developed "generic scripting interface (GSI)" realized. Which adds an additional abstraction layer whose use I find at least questionable. It also seems to make it difficult to deploy a Python API documentation. Besides, this makes the Python API practically not pythonic.

In my own thinking about a Python layout package, I ended up with the [lib2geom](https://gitlab.com/inkscape/lib2geom) geometry from inkscape. The design seems relatively modern and is logically optimized for dealing with SVG. Cons there are some disadvantages, the Python interface is only Python 2. IO is not a part but it seems possible to use the IO part of inkscape. Thus, the choice of Shapely for me seems pretty sensible. I had just read from Shapely a few weeks ago and had probably been too unsettled by the GEO background (I had considered the whole thing too much a CAD problem).

A few more comments about the project:
1. Is help required? Is there a roadmap or TODO list? I'm definitely interested in contributing.

2. gdsCAD seems unmaintained are there any considerations to integrate the code / functionality into gdshelpers?

3. Was there any contact to [PHIDL](https://github.com/amccaugh/phidl)? The goals seem pretty congruent to me. So developer resources could be bundled.
The same applies to [ZeroPDK](https://github.com/lightwave-lab/zeropdk). Also quite new and based on Klayout.
or [nazca](https://nazca-design.org/) also seems to go in the direction but has no git repo (not found?).

(Please excuse my bad english)

**Comment by HelgeGehring** [comment]
Hey, thanks for your comments!
Help is always very welcome and the project mostly grows on what is needed, therefore we don't have a clear roadmap at the moment.
About gdsCAD, I recently implemented a direct export for GDSII without using any library (will be part of the next version). Therefore, I think gdsCAD will be removed in the future, especially because it's not easily installable in Python 3 via pip at the moment.
I think compared to the other approaches you mentioned, the usage of well-maintained shapely-package as the base is a strength of our project, as it makes the structure generation quite flexible and the fracturing algorithms allow easy programming of export algorithms.
One way to contribute would be to add new parts, as I'd guess you might need some additional ones. Also, if you need another file format, writing an export function would be an idea (I recently also added .dxf). Another thing is the documentation, not all parts and features which are implemented at the moment are explained there yet.
