### ISSUE TITLE
Regression for Waveguide.add_parameterized_path

### ISSUE THREAD

**Issue by fbeutel** [HelgeGehring/gdshelpers#30]
Commit 1f0fa3fbddb90ee100af4d980af23ce7d7f9e743 introduced a different regression. The following works with v1.1.2, but doesn't anymore work as previously with the mentioned commit.

I guess the problem is that it's difficult to distingish whether an array passed as the `width` consists of the individual sampling points or describes slot-waveguides.

The following is a minimal example (adapted from code of @frank-bp ) shows the problem:
```
import numpy as np
from gdshelpers.parts.waveguide import Waveguide
from gdshelpers.parts import Port
from gdshelpers.geometry.chip import Cell

def path_function(t):
    return 10 * t, np.zeros((len(t)))

def width_function(t):
    return 0.5 + t

sample_coordinates = np.linspace(0, 1, 5)
path_vector = np.array(path_function(sample_coordinates)).T
width_vector = np.array(width_function(sample_coordinates)).T

wg = Waveguide.make_at_port(Port([0, 0], 0.5*np.pi, 1))
wg.add_parameterized_path(path=path_vector, width=width_vector,
                          sample_distance=None)

cell=Cell('foo')
cell.add_to_layer(1, wg)
cell.save('foo')
```

Before 1f0fa3fbddb90ee100af4d980af23ce7d7f9e743 this produces a single waveguide with changing width, and afterwards it produces three waveguide rails and two slots.

**Comment by HelgeGehring** [comment]
I'd guess #31 should fix the problem. If no width is provided, the width of the port is used for the whole path, otherwise  `width` is interpreted as a scalar width along the path.
If one wants to use `width` for describing an slot-waveguide, it just needs to be an 2D-array (which is rather unusual as it would be incontinuos to the part before)
@fbeutel what do you think?
