### ISSUE TITLE
GDSIIImport's get_as_shapely does not work properly with cell arrays

### ISSUE THREAD

**Issue by Trajectory989** [HelgeGehring/gdshelpers#64]
If this is run on a cell array, it does not recognize multiple instantiations....only the original copy at the original origin is placed (like just cellarray[0] and not the others....). See the zip.zip file. Use the Top Cell for copy
![image](https://user-images.githubusercontent.com/36524768/151247802-f0e90b3d-3ef8-459f-a6c2-2313bdc4ced7.png)
[zip.zip](https://github.com/HelgeGehring/gdshelpers/files/7945640/zip.zip)

**Comment by nicholasnobile** [comment]
Yep. The code in version [53970dd](https://github.com/HelgeGehring/gdshelpers/commit/53970dd1383f3a6233dc40250b661990c97f1dc6) works for doing a good convert to positive resist function
![image](https://user-images.githubusercontent.com/36524768/151392634-13a55229-bb66-45b3-b192-744ba2ce44ae.png)
```
if positive:
        pcell = Cell("Top")
        pcell.add_to_layer(1, convert_to_positive_resist(parts=cell.get_reduced_layer(1), buffer_radius=2))
        pcell.save(f"{directory}/{filename}_pos", grid_steps_per_micron=10000)
```

**Comment by nicholasnobile** [comment]
Actually, This works well for outputting a design that is made currently in program from a cell object made there. Similar changes need to be made to the GDSIIImport class as was done in 53970dd so that already made designs can be properly imported first as the issue seems to occur at import time as well.
